### ISSUE TITLE
playTurn()

### ISSUE THREAD

**Issue by primaulia** [wdi-sg/tic-tac-toe-tester-darrelltzj#1]
So for every playTurn call, you set the game is done and winnerResults = 3?

That doesn't sound right don't you think?

**Comment by darrelltzj** [comment]
``` 
if (!board.includes(0)) {
    winnerResult = 3
  }
```
checks if board contains 0. If there are "empty spaces" on the board, then winnerResult would be 3, else it remains 0

Have simplified the code to check for draw in the switch-case anyway.
